<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import sanziLogo from './assets/sanzi-logo.png'
import InfoPopover from './components/InfoPopover.vue'

// Information shown by the reusable info popovers.
const INFO_CONTENT = {
  llama: {
    title: 'Llama 3.2 1B',
    paragraphs: [
      'A compact 1-billion-parameter language model developed by Meta. It is designed for instruction following and text-generation tasks while being small enough for local deployment on consumer hardware.',
      'Model context capacity: 128K tokens',
    ],
    link: 'https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct',
  },
  qwen: {
    title: 'Qwen 1.5 0.5B',
    paragraphs: [
      'A lightweight 0.5-billion-parameter language model developed by Alibaba Cloud. Its smaller size makes it suitable for fast and memory-efficient local inference on resource-limited devices.',
      'Model context capacity: 32K tokens',
    ],
    link: 'https://huggingface.co/Qwen/Qwen1.5-0.5B-Chat',
  },
  precision: {
    title: 'Precision',
    paragraphs: [
      'All three modes run locally on Apple Silicon through MPS/Metal. FP16 is the non-quantized baseline, while 8-bit and 4-bit use Metal-based weight quantization to reduce model memory usage. More aggressive quantization can slightly affect model quality.',
    ],
    items: [
      'FP16: 16-bit floating-point baseline.',
      '8-bit Metal: intermediate quantization and memory reduction.',
      '4-bit Metal: stronger quantization and greater weight-memory reduction.',
    ],
  },
  maxOutputTokens: {
    title: 'Max output tokens',
    paragraphs: [
      'Sets the maximum number of new tokens SANZI may generate in one response. Higher values allow longer answers but can increase generation time and memory use.',
      'The current default is 256 tokens, while the user can configure up to 768 tokens.',
      'This is an output limit, not the model’s total context capacity.',
    ],
  },
  temperature: {
    title: 'Temperature',
    paragraphs: [
      'Controls randomness in the response. Lower values make answers more predictable and focused, while higher values allow more variation and creativity.',
      'The default 0.7 provides a balanced level of randomness for general chat.',
    ],
  },
  topP: {
    title: 'Top-p',
    paragraphs: [
      'Controls how many likely word choices SANZI considers when generating the next part of a response. Lower values make answers more focused and predictable, while higher values allow more variety.',
      'The default 0.9 gives a good balance between focus and diversity.',
    ],
  },
  seed: {
    title: 'Seed',
    paragraphs: [
      'Sets the starting point for randomness during generation. Using the same seed with the same prompt and settings helps produce reproducible results.',
      'The default value 42 is simply a commonly used convention; it has no special advantage for the model.',
    ],
  },
  loadTime: {
    title: 'Load time',
    paragraphs: [
      'The time required to load the tokenizer and model with the selected precision and prepare it for inference. The value can vary between runs depending on system memory, caching, and initialization overhead.',
    ],
  },
  tokens: {
    title: 'Token information',
    definitions: [
      {
        term: 'User tokens',
        description: 'Tokens contained only in the user message belonging to that conversation round.',
      },
      {
        term: 'Output tokens',
        description: 'Tokens generated by SANZI for that conversation round.',
      },
      {
        term: 'Round total',
        description: 'User tokens + SANZI output tokens for that round.',
      },
      {
        term: 'Conversation tokens used',
        description:
          'The current token usage of the complete saved conversation, including the additional chat-formatting/context tokens required by the model.',
      },
      {
        term: 'Remaining',
        description: 'The amount of context still available before SANZI reaches its operational safe token limit.',
      },
      {
        term: 'Safe token limit — 2500',
        description:
          'SANZI’s conservative operational input/context limit for reliable local inference on the current deployment environment. It is separate from the much larger theoretical context capacity of the model.',
      },
      {
        term: 'Model capacity',
        description:
          'The theoretical context capacity supported by the selected language model, such as 32K for Qwen or 128K for Llama.',
      },
    ],
  },
}

// Fallback model metadata used before backend state is loaded.
const DEFAULT_MODELS = [
  {
    id: 'llama',
    name: 'Llama 3.2 1B',
    full_name: 'Llama-3.2-1B-Instruct',
    description: 'More capable reasoning and instruction following.',
    parameters: '1B',
    context_capacity: '128K tokens',
  },
  {
    id: 'qwen',
    name: 'Qwen 1.5 0.5B',
    full_name: 'Qwen1.5-0.5B-Chat',
    description: 'Faster, lighter responses with the smallest memory footprint.',
    parameters: '0.5B',
    context_capacity: '32K tokens',
  },
]

const DEFAULT_PRECISIONS = [
  {
    id: 'fp16',
    name: 'FP16',
    description: 'Standard 16-bit floating-point model loading.',
    available: true,
  },
  {
    id: 'int8',
    name: '8-bit Metal',
    description: '8-bit weight quantization for reduced model memory usage.',
    available: true,
  },
  {
    id: 'int4',
    name: '4-bit Metal',
    description: '4-bit weight quantization for greater model memory reduction.',
    available: true,
  },
]

const STARTER_PROMPT_POOL = [
  {
    title: 'Explain a topic simply',
    prompt: 'Explain the following topic in simple terms: ',
  },
  {
    title: 'Summarize a text',
    prompt: 'Summarize the following text and keep the key points: ',
  },
  {
    title: 'Help me with code',
    prompt: 'Help me understand or solve the following programming problem: ',
  },
  {
    title: 'Generate ideas',
    prompt: 'Generate several practical ideas about: ',
  },
  {
    title: 'Compare two things',
    prompt: 'Compare the following two things and explain their main differences: ',
  },
  {
    title: 'Explain step by step',
    prompt: 'Explain the following step by step: ',
  },
  {
    title: 'Improve my writing',
    prompt: 'Improve the following text while keeping its original meaning: ',
  },
  {
    title: 'Make it shorter',
    prompt: 'Rewrite the following text in a shorter and clearer way: ',
  },
  {
    title: 'Ask me quiz questions',
    prompt: 'Create a short quiz about the following topic: ',
  },
  {
    title: 'Teach me a concept',
    prompt: 'Teach me the following concept in an easy-to-understand way: ',
  },
  {
    title: 'Solve a problem',
    prompt: 'Help me solve the following problem and explain the reasoning: ',
  },
  {
    title: 'Write a short note',
    prompt: 'Write a clear and concise note about: ',
  },
  {
    title: 'List key points',
    prompt: 'List the most important points about: ',
  },
  {
    title: 'Explain advantages and disadvantages',
    prompt: 'Explain the main advantages and disadvantages of: ',
  },
  {
    title: 'Create a study plan',
    prompt: 'Create a simple study plan for learning: ',
  },
  {
    title: 'Brainstorm solutions',
    prompt: 'Suggest several possible solutions for the following problem: ',
  },
  {
    title: 'Explain code',
    prompt: 'Explain what the following code does in simple terms: ',
  },
  {
    title: 'Find possible mistakes',
    prompt: 'Review the following and identify possible mistakes or problems: ',
  },
  {
    title: 'Give practical examples',
    prompt: 'Explain the following topic using practical examples: ',
  },
  {
    title: 'Create an outline',
    prompt: 'Create a clear outline for the following topic: ',
  },
]

function selectStarterPrompts(previousPrompts = []) {
  const shuffledPool = [...STARTER_PROMPT_POOL]
  for (let index = shuffledPool.length - 1; index > 0; index -= 1) {
    const randomIndex = Math.floor(Math.random() * (index + 1))
    const currentPrompt = shuffledPool[index]
    shuffledPool[index] = shuffledPool[randomIndex]
    shuffledPool[randomIndex] = currentPrompt
  }

  const previousTitles = new Set(previousPrompts.map((prompt) => prompt.title))
  const selectedPrompts = shuffledPool.slice(0, 4)
  if (
    selectedPrompts.length === previousTitles.size &&
    selectedPrompts.every((prompt) => previousTitles.has(prompt.title))
  ) {
    selectedPrompts[3] = shuffledPool.find((prompt) => !previousTitles.has(prompt.title))
  }

  return selectedPrompts
}

// Reactive application state mirrors the backend state.
const models = ref(DEFAULT_MODELS)
const precisions = ref(DEFAULT_PRECISIONS)
const selectedModel = ref('qwen')
const selectedPrecision = ref('fp16')
const activeModel = ref(null)
const activePrecision = ref(null)
const poweredOn = ref(false)
const device = ref('not loaded')
const loadTimeSeconds = ref(null)
const conversation = ref([])
const contextStatus = ref({
  context_tokens: 0,
  remaining: 2500,
  safe_limit: 2500,
  model_capacity: '32K tokens',
  status: 'normal',
})
const settings = ref({ max_length: 256, seed: 42, temperature: 0.7, top_p: 0.9 })
const message = ref('')
const busy = ref(false)
const busyLabel = ref('')
const error = ref('')
const removeCount = ref(1)
const historyOpen = ref(false)
const aboutOpen = ref(false)
const mobilePanelOpen = ref(false)
const roundToRemove = ref(null)
const removingRound = ref(false)
const continuingResponse = ref(false)
const chatViewport = ref(null)
const messageBox = ref(null)
const followNewestMessage = ref(true)
const openInfo = ref(null)
const visibleStarterPrompts = ref(selectStarterPrompts())

// Derived UI state
const selected = computed(() => models.value.find((model) => model.id === selectedModel.value))
const selectedPrecisionInfo = computed(() =>
  precisions.value.find((precision) => precision.id === selectedPrecision.value),
)
const activePrecisionInfo = computed(() =>
  precisions.value.find((precision) => precision.id === activePrecision.value),
)
const isGenerating = computed(
  () =>
    busy.value &&
    conversation.value.at(-1)?.role === 'assistant' &&
    (conversation.value.at(-1)?.pending || continuingResponse.value),
)
const canSend = computed(
  () =>
    poweredOn.value &&
    !busy.value &&
    contextStatus.value.context_tokens < contextStatus.value.safe_limit &&
    message.value.trim().length > 0,
)
const rounds = computed(() => Math.floor(conversation.value.length / 2))

// Synchronize the frontend with one backend state snapshot
function syncState(state) {
  // Apply one authoritative backend snapshot after any state-changing request.
  models.value = state.models ?? models.value
  precisions.value = (state.precisions ?? precisions.value).map((precision) => ({
    ...precision,
    description:
      DEFAULT_PRECISIONS.find((defaultPrecision) => defaultPrecision.id === precision.id)?.description ??
      precision.description,
  }))
  selectedModel.value = state.selected_model ?? selectedModel.value
  selectedPrecision.value = state.selected_precision ?? selectedPrecision.value
  activeModel.value = state.active_model
  activePrecision.value = state.active_precision
  poweredOn.value = state.powered_on
  device.value = state.device
  loadTimeSeconds.value = state.load_time_seconds ?? null
  settings.value = state.settings ?? settings.value
  conversation.value = state.conversation ?? []
  contextStatus.value = state.context_status ?? contextStatus.value
}

// Send a JSON request to the local Python backend
async function api(path, options = {}) {
  // Allow slightly longer than the backend's 120-second generation limit.
  const controller = new AbortController()
  const timeout = window.setTimeout(() => controller.abort(), 135000)
  let response
  try {
    response = await fetch(path, {
      ...options,
      signal: controller.signal,
      headers: { 'Content-Type': 'application/json', ...(options.headers ?? {}) },
    })
  } catch (err) {
    if (err.name === 'AbortError') {
      throw new Error('The request took too long and was stopped. Try a smaller max length or use Qwen 0.5B.')
    }
    throw err
  } finally {
    window.clearTimeout(timeout)
  }
  let payload = {}
  try {
    payload = await response.json()
  } catch {
    // A useful fallback when the local server closes unexpectedly.
  }
  if (!response.ok) throw new Error(payload.error || `Request failed (${response.status})`)
  return payload
}

function setError(value) {
  error.value = value instanceof Error ? value.message : String(value)
  window.setTimeout(() => {
    if (error.value === (value instanceof Error ? value.message : String(value))) error.value = ''
  }, 7000)
}

async function loadState() {
  try {
    syncState(await api('/api/state'))
    followNewestMessage.value = true
    await scrollToBottom()
  } catch (err) {
    setError(`Cannot reach the Python backend. ${err.message}`)
  }
}

// Model power and configuration controls
async function togglePower() {
  if (busy.value) return
  busy.value = true
  busyLabel.value = poweredOn.value
    ? 'Releasing model memory…'
    : `Loading ${selected.value?.name ?? 'model'} (${selectedPrecisionInfo.value?.name ?? 'FP16'})…`
  error.value = ''
  try {
    const state = await api('/api/power', {
      method: 'POST',
      body: JSON.stringify({
        on: !poweredOn.value,
        model_id: selectedModel.value,
        precision: selectedPrecision.value,
      }),
    })
    syncState(state)
  } catch (err) {
    setError(err)
  } finally {
    busy.value = false
    busyLabel.value = ''
  }
}

async function choosePrecision(precisionId) {
  if (busy.value || precisionId === selectedPrecision.value) return
  const precision = precisions.value.find((item) => item.id === precisionId)
  if (!precision?.available) return
  // Restore the previous selection if the model reload fails.
  const previous = selectedPrecision.value
  selectedPrecision.value = precisionId
  if (!poweredOn.value) return

  busy.value = true
  busyLabel.value = `Reloading in ${precision.name}…`
  try {
    syncState(
      await api('/api/precision', {
        method: 'POST',
        body: JSON.stringify({ precision: precisionId }),
      }),
    )
  } catch (err) {
    selectedPrecision.value = previous
    await loadState()
    setError(err)
  } finally {
    busy.value = false
    busyLabel.value = ''
  }
}

async function chooseModel(modelId) {
  if (busy.value || modelId === selectedModel.value) return
  const previous = selectedModel.value
  selectedModel.value = modelId

  busy.value = true
  busyLabel.value = poweredOn.value
    ? `Switching to ${models.value.find((item) => item.id === modelId)?.name}…`
    : `Updating context for ${models.value.find((item) => item.id === modelId)?.name}…`
  try {
    syncState(
      await api('/api/model', {
        method: 'POST',
        body: JSON.stringify({ model_id: modelId }),
      }),
    )
  } catch (err) {
    selectedModel.value = previous
    await loadState()
    setError(err)
  } finally {
    busy.value = false
    busyLabel.value = ''
  }
}

// Chat and conversation management
async function sendMessage(prefill) {
  if (typeof prefill === 'string') message.value = prefill
  const prompt = message.value.trim()
  if (
    !prompt ||
    !poweredOn.value ||
    busy.value ||
    contextStatus.value.context_tokens >= contextStatus.value.safe_limit
  ) {
    return
  }

  // Show the pending round immediately while the serialized backend generates.
  message.value = ''
  conversation.value.push({ role: 'user', content: prompt }, { role: 'assistant', pending: true })
  busy.value = true
  busyLabel.value = 'SANZI is typing…'
  await scrollToBottom()

  try {
    const result = await api('/api/chat', {
      method: 'POST',
      body: JSON.stringify({ message: prompt, settings: settings.value }),
    })
    conversation.value = result.conversation
    contextStatus.value = result.context_status ?? contextStatus.value
  } catch (err) {
    conversation.value.splice(-2)
    message.value = prompt
    setError(err)
  } finally {
    busy.value = false
    busyLabel.value = ''
    await scrollToBottom()
    messageBox.value?.focus()
  }
}

async function continueResponse() {
  const latest = conversation.value.at(-1)
  if (
    busy.value ||
    latest?.role !== 'assistant' ||
    !['output_limit', 'time_limit', 'incomplete'].includes(latest.continuation_reason)
  ) {
    return
  }

  // Continuations extend the latest assistant card instead of adding a round.
  busy.value = true
  continuingResponse.value = true
  busyLabel.value = 'SANZI is continuing the response…'
  error.value = ''
  await scrollToBottom()

  try {
    const result = await api('/api/chat/continue', {
      method: 'POST',
      body: JSON.stringify({ settings: settings.value }),
    })
    conversation.value = result.conversation
    contextStatus.value = result.context_status ?? contextStatus.value
  } catch (err) {
    setError(err)
  } finally {
    continuingResponse.value = false
    busy.value = false
    busyLabel.value = ''
    await scrollToBottom()
    messageBox.value?.focus()
  }
}

async function useStarterPrompt(starterPrompt) {
  if (!poweredOn.value || busy.value || conversation.value.length > 0) return

  const currentMessage = message.value
  if (!currentMessage.startsWith(starterPrompt)) {
    message.value = currentMessage.trim()
      ? `${starterPrompt}${currentMessage.trimStart()}`
      : starterPrompt
  }

  await nextTick()
  const textarea = messageBox.value
  if (!textarea) return
  textarea.style.height = 'auto'
  textarea.style.height = `${Math.min(textarea.scrollHeight, 160)}px`
  textarea.focus()
  const cursorPosition = message.value.length
  textarea.setSelectionRange(cursorPosition, cursorPosition)
}

function shuffleStarterPrompts() {
  if (!poweredOn.value || busy.value || conversation.value.length > 0) return
  visibleStarterPrompts.value = selectStarterPrompts(visibleStarterPrompts.value)
}

async function clearConversation() {
  if (!conversation.value.length || busy.value) return
  try {
    syncState(await api('/api/conversation', { method: 'DELETE' }))
    followNewestMessage.value = true
    historyOpen.value = false
  } catch (err) {
    setError(err)
  }
}

async function removeRounds() {
  if (!rounds.value || busy.value) return
  try {
    syncState(
      await api('/api/conversation/remove', {
        method: 'POST',
        body: JSON.stringify({ rounds: removeCount.value }),
      }),
    )
    removeCount.value = 1
    historyOpen.value = false
  } catch (err) {
    setError(err)
  }
}

function requestRoundRemoval(messageIndex) {
  if (busy.value || removingRound.value) return
  roundToRemove.value = Math.floor(messageIndex / 2)
}

function cancelRoundRemoval() {
  if (!removingRound.value) roundToRemove.value = null
}

async function confirmRoundRemoval() {
  if (roundToRemove.value === null || busy.value || removingRound.value) return

  // Preserve the reader's scroll position when a round is removed above it.
  const roundIndex = roundToRemove.value
  const viewport = chatViewport.value
  const previousScrollTop = viewport?.scrollTop ?? 0
  const previousScrollHeight = viewport?.scrollHeight ?? 0
  const wasFollowingNewest = followNewestMessage.value
  const roundCards = viewport
    ? [...viewport.querySelectorAll(`[data-round-index="${roundIndex}"]`)]
    : []
  const viewportTop = viewport?.getBoundingClientRect().top ?? 0
  const removedAboveViewport =
    roundCards.length > 0 && roundCards.at(-1).getBoundingClientRect().bottom <= viewportTop

  removingRound.value = true
  try {
    syncState(
      await api('/api/conversation/remove-round', {
        method: 'POST',
        body: JSON.stringify({ round_index: roundIndex }),
      }),
    )
    roundToRemove.value = null
    await nextTick()

    if (viewport) {
      if (wasFollowingNewest) {
        viewport.scrollTop = viewport.scrollHeight
      } else if (removedAboveViewport) {
        const removedHeight = previousScrollHeight - viewport.scrollHeight
        viewport.scrollTop = Math.max(0, previousScrollTop - removedHeight)
      } else {
        viewport.scrollTop = previousScrollTop
      }
    }
  } catch (err) {
    setError(err)
  } finally {
    removingRound.value = false
  }
}

// Composer, scrolling, and information-popover helpers
function onComposerKeydown(event) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    sendMessage()
  }
}

function autoSize(event) {
  event.target.style.height = 'auto'
  event.target.style.height = `${Math.min(event.target.scrollHeight, 160)}px`
}

function onChatScroll() {
  const viewport = chatViewport.value
  if (!viewport) return
  const distanceFromBottom = viewport.scrollHeight - viewport.scrollTop - viewport.clientHeight
  followNewestMessage.value = distanceFromBottom <= 60
}

async function scrollToBottom() {
  await nextTick()
  if (chatViewport.value && followNewestMessage.value) {
    chatViewport.value.scrollTop = chatViewport.value.scrollHeight
  }
}

function toggleInfo(infoId) {
  openInfo.value = openInfo.value === infoId ? null : infoId
}

function closeInfo() {
  openInfo.value = null
}

function onGlobalKeydown(event) {
  if (event.key === 'Escape') closeInfo()
}

// Component lifecycle
onMounted(() => {
  // Load backend state once and close information popovers on outside clicks.
  document.addEventListener('click', closeInfo)
  document.addEventListener('keydown', onGlobalKeydown)
  loadState()
})

onBeforeUnmount(() => {
  document.removeEventListener('click', closeInfo)
  document.removeEventListener('keydown', onGlobalKeydown)
})
</script>

<template>
  <div class="app-shell">
    <aside class="control-panel" :class="{ 'mobile-open': mobilePanelOpen }">
      <div class="project-title">
        <div class="sanzi-brand">
          <img :src="sanziLogo" alt="SANZI mascot" class="sanzi-main-logo" />
          <div>
            <h1>SANZI</h1>
            <p>University project</p>
          </div>
        </div>
        <button class="mobile-close" aria-label="Close settings" @click="mobilePanelOpen = false">Close</button>
      </div>

      <div class="panel-scroll" :class="{ locked: isGenerating }">
        <p v-if="isGenerating" class="settings-lock-message">
          Generating response… Settings are temporarily locked.
        </p>

        <section class="control-section">
          <h2>Model</h2>
          <div
            v-for="model in models"
            :key="model.id"
            class="model-option-wrap"
          >
            <label class="model-option" :class="{ selected: selectedModel === model.id }">
              <input
                type="radio"
                name="model"
                :value="model.id"
                :checked="selectedModel === model.id"
                :disabled="busy"
                @change="chooseModel(model.id)"
              />
              <span>
                <strong>{{ model.name }}</strong>
                <small>{{ model.full_name }}</small>
              </span>
            </label>
            <InfoPopover
              :open="openInfo === model.id"
              :label="model.name"
              :content="INFO_CONTENT[model.id]"
              @toggle="toggleInfo(model.id)"
              @close="closeInfo"
            />
          </div>
        </section>

        <section class="control-section">
          <div class="control-title-with-info">
            <h2>Precision</h2>
            <InfoPopover
              :open="openInfo === 'precision'"
              label="Precision"
              :content="INFO_CONTENT.precision"
              @toggle="toggleInfo('precision')"
              @close="closeInfo"
            />
          </div>
          <label
            v-for="precision in precisions"
            :key="precision.id"
            class="model-option"
            :class="{ selected: selectedPrecision === precision.id, unavailable: !precision.available }"
          >
            <input
              type="radio"
              name="precision"
              :value="precision.id"
              :checked="selectedPrecision === precision.id"
              :disabled="busy || !precision.available"
              @change="choosePrecision(precision.id)"
            />
            <span>
              <strong>{{ precision.name }}</strong>
              <small>{{ precision.description }}</small>
            </span>
          </label>
          <p
            v-if="precisions.some((precision) => ['int8', 'int4'].includes(precision.id) && !precision.available)"
            class="option-note"
          >
            Metal quantization requires Apple Silicon and MPS.
          </p>
        </section>

        <section class="control-section">
          <h2>Generation settings</h2>

          <label class="setting-row">
            <span class="setting-label-with-info">
              <span>Max output tokens: {{ settings.max_length }}</span>
              <InfoPopover
                :open="openInfo === 'maxOutputTokens'"
                label="Max output tokens"
                :content="INFO_CONTENT.maxOutputTokens"
                @toggle="toggleInfo('maxOutputTokens')"
                @close="closeInfo"
              />
            </span>
            <input v-model.number="settings.max_length" type="range" min="20" max="768" step="4" :disabled="busy" />
          </label>
          <label class="setting-row">
            <span class="setting-label-with-info">
              <span>Temperature: {{ settings.temperature.toFixed(1) }}</span>
              <InfoPopover
                :open="openInfo === 'temperature'"
                label="Temperature"
                :content="INFO_CONTENT.temperature"
                @toggle="toggleInfo('temperature')"
                @close="closeInfo"
              />
            </span>
            <input v-model.number="settings.temperature" type="range" min="0.1" max="1.5" step="0.1" :disabled="busy" />
          </label>
          <label class="setting-row">
            <span class="setting-label-with-info">
              <span>Top-p: {{ settings.top_p.toFixed(2) }}</span>
              <InfoPopover
                :open="openInfo === 'topP'"
                label="Top-p"
                :content="INFO_CONTENT.topP"
                @toggle="toggleInfo('topP')"
                @close="closeInfo"
              />
            </span>
            <input v-model.number="settings.top_p" type="range" min="0.1" max="1" step="0.05" :disabled="busy" />
          </label>
          <label class="number-field">
            <span class="number-label-with-info">
              <span>Seed</span>
              <InfoPopover
                :open="openInfo === 'seed'"
                label="Seed"
                :content="INFO_CONTENT.seed"
                @toggle="toggleInfo('seed')"
                @close="closeInfo"
              />
            </span>
            <input v-model.number="settings.seed" type="number" min="0" max="1000000" :disabled="busy" />
          </label>
        </section>
      </div>

      <p class="local-note">The models run locally on this computer.</p>
    </aside>

    <main class="chat-area">
      <header class="topbar">
        <button class="mobile-menu" aria-label="Open settings" @click="mobilePanelOpen = true">Settings</button>
        <div class="status-group">
          <span class="status-light" :class="{ online: poweredOn, loading: busy }"></span>
          <div class="status-copy">
            <strong>{{ poweredOn ? 'Model is running' : 'Model is off' }}</strong>
            <div class="status-detail-row">
              <small>
                <template v-if="poweredOn">
                  {{ selected?.full_name }} · {{ activePrecisionInfo?.name ?? 'FP16' }} ({{ device }})
                  <template v-if="loadTimeSeconds !== null">
                    · Load time: {{ loadTimeSeconds.toFixed(2) }} s
                  </template>
                </template>
                <template v-else>Select a model and turn it on</template>
              </small>
              <InfoPopover
                v-if="poweredOn && loadTimeSeconds !== null"
                placement="status"
                :open="openInfo === 'loadTime'"
                label="Load time"
                :content="INFO_CONTENT.loadTime"
                @toggle="toggleInfo('loadTime')"
                @close="closeInfo"
              />
            </div>
          </div>
        </div>

        <div class="header-actions">
          <button class="secondary-button" @click="aboutOpen = true">About</button>
          <div class="history-wrap">
            <button class="secondary-button" :disabled="busy || !rounds" @click="historyOpen = !historyOpen">
              Manage history ({{ rounds }})
            </button>
            <div v-if="historyOpen" class="history-popover">
              <h3>Conversation history</h3>
              <p>{{ rounds }} complete round{{ rounds === 1 ? '' : 's' }}</p>
              <label>
                Number of rounds to remove from the beginning
                <span>
                  <input v-model.number="removeCount" type="number" min="1" :max="rounds" />
                  <button @click="removeRounds">Remove</button>
                </span>
              </label>
              <button class="danger-button" @click="clearConversation">Clear all messages</button>
            </div>
          </div>
          <button class="primary-button" :class="{ stop: poweredOn }" :disabled="busy" @click="togglePower">
            {{ poweredOn ? 'Turn off' : 'Turn on' }}
          </button>
        </div>
      </header>

      <div ref="chatViewport" class="chat-viewport" @scroll="onChatScroll">
        <section v-if="!poweredOn || conversation.length === 0" class="empty-state">
          <img :src="sanziLogo" alt="SANZI mascot" class="sanzi-welcome-logo" />
          <p class="welcome-greeting">Hi! I’m SANZI.</p>
          <p>
            A local LLM assistant running Llama 3.2 1B or Qwen 1.5 0.5B directly on your Apple Silicon
            Mac. SANZI was developed and tested on a 2020 MacBook Air with Apple M1 and 8 GB memory.
          </p>
          <p v-if="!poweredOn" class="model-off-status">The model is currently off.</p>
          <p v-if="!poweredOn" class="help-text">
            Choose a model and your preferred configuration in Settings, then click
            “<span class="welcome-turn-on">Turn on</span>” to
            {{ rounds ? 'continue chatting' : 'start chatting' }}.
          </p>
          <p v-else class="help-text">The model is ready. Enter a message below.</p>
          <div v-if="poweredOn && conversation.length === 0" class="starter-prompts-wrap">
            <div class="starter-prompts-toolbar">
              <button
                type="button"
                class="shuffle-prompts-button"
                :disabled="busy"
                @click="shuffleStarterPrompts"
              >
                ↻ Shuffle prompts
              </button>
            </div>
            <div class="starter-prompts" aria-label="Starter prompts">
              <button
                v-for="starter in visibleStarterPrompts"
                :key="starter.title"
                type="button"
                class="starter-prompt-card"
                :disabled="busy"
                @click="useStarterPrompt(starter.prompt)"
              >
                <strong>{{ starter.title }}</strong>
                <span>{{ starter.prompt }}</span>
              </button>
            </div>
          </div>
        </section>

        <section v-else class="message-list">
          <article
            v-for="(item, index) in conversation"
            :key="index"
            class="message"
            :class="item.role"
            :data-round-index="Math.floor(index / 2)"
          >
            <div class="message-content">
              <button
                type="button"
                class="round-remove-trigger"
                :aria-label="`Remove conversation round ${Math.floor(index / 2) + 1}`"
                title="Remove round"
                :disabled="busy || removingRound"
                @click="requestRoundRemoval(index)"
              >
                Remove
              </button>
              <strong class="message-role" :class="{ 'sanzi-message-role': item.role === 'assistant' }">
                <template v-if="item.role === 'assistant'">
                  <img :src="sanziLogo" alt="" class="sanzi-message-logo" />
                  <span>SANZI</span>
                </template>
                <template v-else>You</template>
              </strong>
              <p v-if="item.pending" class="pending-message">SANZI is typing...</p>
              <p v-else>{{ item.content }}</p>
              <small v-if="item.role === 'assistant' && item.token_usage">
                User tokens: {{ item.token_usage.user }} | Output tokens: {{ item.token_usage.output }} |
                Round total: {{ item.token_usage.round_total }}
              </small>
              <div
                v-if="
                  item.role === 'assistant' &&
                  index === conversation.length - 1 &&
                  ['output_limit', 'time_limit', 'incomplete'].includes(item.continuation_reason)
                "
                class="continuation-notice"
              >
                <small v-if="item.continuation_reason === 'output_limit'">
                  Response reached the output-token limit. Click “Continue response” to continue generating.
                </small>
                <small v-else-if="item.continuation_reason === 'time_limit'">
                  Generation paused after the two-minute safety limit. Click “Continue response” to continue generating.
                </small>
                <small v-else>
                  This response may be incomplete. Click “Continue response” to continue generating.
                </small>
                <button
                  type="button"
                  class="continue-response-button"
                  :disabled="busy"
                  @click="continueResponse"
                >
                  Continue response
                </button>
              </div>
            </div>
          </article>
        </section>
      </div>

      <footer class="composer-zone">
        <div v-if="error" class="error-message">{{ error }}<button @click="error = ''">Close</button></div>
        <div v-if="busyLabel" class="busy-label">{{ busyLabel }}</div>
        <div class="context-status-wrap">
          <p class="context-status">
            Conversation tokens used: {{ contextStatus.context_tokens }} |
            Remaining: {{ contextStatus.remaining }} (Safe token limit: {{ contextStatus.safe_limit }}) |
            Model capacity: {{ contextStatus.model_capacity }}
          </p>
          <InfoPopover
            placement="tokens"
            :open="openInfo === 'tokens'"
            label="Token information"
            :content="INFO_CONTENT.tokens"
            @toggle="toggleInfo('tokens')"
            @close="closeInfo"
          />
        </div>
        <p v-if="contextStatus.status === 'approaching'" class="context-warning approaching">
          Conversation is approaching the safe token limit. Consider removing earlier rounds or clearing history.
        </p>
        <p v-else-if="contextStatus.status === 'blocked'" class="context-warning blocked">
          The saved conversation has reached SANZI’s safe token limit. Remove earlier rounds or clear history before
          sending another message.
        </p>
        <div class="composer" :class="{ disabled: !poweredOn }">
          <textarea
            ref="messageBox"
            v-model="message"
            rows="1"
            maxlength="8000"
            :disabled="!poweredOn || busy"
            :placeholder="poweredOn ? `Message ${selected?.name}…` : 'Turn on a model to start chatting…'"
            @keydown="onComposerKeydown"
            @input="autoSize"
          ></textarea>
          <button class="primary-button send-button" :disabled="!canSend" @click="sendMessage()">Send</button>
        </div>
        <p class="composer-help">Press Enter to send. Use Shift + Enter for a new line.</p>
      </footer>
    </main>
    <div v-if="mobilePanelOpen" class="panel-backdrop" @click="mobilePanelOpen = false"></div>

    <div v-if="roundToRemove !== null" class="about-backdrop" @click="cancelRoundRemoval">
      <section
        class="round-remove-dialog"
        role="dialog"
        aria-modal="true"
        aria-labelledby="round-remove-title"
        @click.stop
      >
        <h2 id="round-remove-title">Remove this conversation round?</h2>
        <p>Both your message and SANZI’s response will be removed.</p>
        <div class="round-remove-actions">
          <button class="secondary-button" :disabled="removingRound" @click="cancelRoundRemoval">Cancel</button>
          <button class="danger-button" :disabled="removingRound" @click="confirmRoundRemoval">
            {{ removingRound ? 'Removing…' : 'Remove' }}
          </button>
        </div>
      </section>
    </div>

    <div v-if="aboutOpen" class="about-backdrop" @click="aboutOpen = false">
      <section
        class="about-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="about-title"
        @click.stop
      >
        <div class="about-header">
          <h2 id="about-title">About SANZI</h2>
          <button class="secondary-button" aria-label="Close About" @click="aboutOpen = false">Close</button>
        </div>

        <p class="about-project">Project Seminar Hardware for Neural Networks — SoSe 2026</p>
        <p><strong>Topic:</strong> Deployment Tiny LLM on personal PC</p>
        <p><strong>Supervisor:</strong> M.Sc. Jingcun Wang</p>

        <p>
          SANZI is a university project exploring the deployment of tiny language models directly on consumer
          hardware. The application supports local inference with Llama 3.2 1B and Qwen 1.5 0.5B, configurable
          generation parameters, conversation management, model switching, runtime memory safeguards, and 8-bit
          and 4-bit Metal quantized inference.
        </p>

        <h3>Development and test hardware</h3>
        <p>2020 MacBook Air<br />Apple M1<br />8 GB memory</p>

        <h3>Developed by</h3>
        <p>Muhammad Hasan Al Banna<br />Matriculation No.: 2951869</p>
      </section>
    </div>
  </div>
</template>
